export const CHAT_STATE = {
    STARTING: 0,
    WAITING_FOR_RECOMMENDATION_TYPE: 1,
    WAITING_FOR_MOVIE_NAME: 2,
    WAITING_FOR_SELECTION: 3,
    WAITING_FOR_GENRE: 4,
    FINISHED_INPUT_MOVIE_NAME: 5,
    FINISHED: 6,
  };
  
export const RECOMMENDATION_TYPE = {
    MOVIE_NAME: 0,
    GENRE: 1,
};

export const GENRES = [
    "animation",
    "news",
    "action",
    "history",
    "family",
    "thriller",
    "fantasy",
    "horror",
    "music",
    "mystery",
    "war",
    "drama",
    "talk-show",
    "game-show",
    "talk-show",
    "musical",
    "crime",
    "romance",
    "biography",
    "comedy",
    "reality-tv",
    "horror",
    "adventure",
    "sci-fi",
    "sport",
    "adult",
    "western",
    "film-noir",
    "sport",
]